title: Ferrari passion
email:  kirilov.evgeni@gmail.com
description: Hi there Ferrari fans!
baseurl: ""
url: ""
github_username:  kirilof93

# Build settings
plugins:
  - jekyll-feed


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
